baseURL = "https://www.randomonamour.fr/"
languageCode = "fr-fr"
title = "rando mon amour"
theme = "chamonix"

[params]

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/randomonamour"


[menu]

  [[menu.top]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.top]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.top]]
    name = "A propos"
    url = "/about-us/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
  
[permalinks]
  posts = "/:slug/"
  pages = "/:filename/"

[imaging]
resampleFilter = "lanczos"
quality = 80
anchor = "smart"
