baseURL = "https://www.randomonamour.fr/"
languageCode = "fr-fr"
title = "rando mon amour"
theme = "chamonix"

[params]

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/randomonamour"


[menu]

  [[menu.top]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.top]]
    name = "A propos"
    url = "/about/"
    weight = 2

  [[menu.top]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[imaging]
resampleFilter = "lanczos"
quality = 80
anchor = "smart"
