---
name: 🚀 Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: 🚚 Checkout latest code
        uses: actions/checkout@v2

      - name: 🛠 Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: 👷 Build website
        run: hugo --minify

      - name: 📡 Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: www/
          local-dir: ./public/
